baseURL = "https://lenhanpham.github.io/"
defaultcontentlanguage = "en"
languageCode = "en-us" 
languageName = "en-us"
paginate = 4
theme = "lenhantheme"
title = "Nhan's everything"


disqusShortname = ""
googleAnalytics = ""
pygmentsUseClasses = true

[author]
name = "Le Nhan Pham"

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[[menu.main]]
  identifier = "home"
  name = "Home"
  url = "/"
  weight = 1
[[menu.main]]
  identifier = "CV"
  name = "CV"
  url = "/CV/"
  weight = 2
[[menu.main]]
  identifier = "research"
  name = "Research"
  url = "/research/"
  weight = 3
[[menu.main]]
  identifier = "publication"
  name = "Publication"
  url = "/publication/"
  weight = 4
  [[menu.main]]
  identifier = "posts"
  name = "Post"
  url = "/post/"
  weight = 5
#[[menu.main]]
#  identifier = "programing"
#  name = "Programing"
#  url = "/programing/"
#  weight = 5
#[[menu.main]]
#  identifier = "archives"
# name = "Archives"
# url = "/post/"
# weight = 6 
# [[menu.main]]
# identifier = "vietnamese"
# name = "Tiếng Việt"
# url = "/vietnamese/"
# weight = 7  


[params]
  custom_css = []
  description = "Personal website of Le Nhan Pham"
  enable_mathjax = true
  footnote = "<a class=link href=https://github.com/lenhanpham target=_blank>GitHub</a>, <a class=link href=https://twitter.com/LeNhanChem target=_blank>Twitter</a> or <a class=link href=/index.xml>RSS</a> | <a class=link href=https://creativecommons.org/licenses/by-nc-sa/4.0 target=_blank rel=noopener>CC BY-NC-SA 4.0</a>"
  keywords = ["hugo", "latex", "theme"]
